# Generated by Django 5.2.5 on 2025-09-01 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст цитаты')),
                ('source', models.CharField(max_length=255, verbose_name='Произведение')),
                ('source_type', models.CharField(choices=[('book', 'Книга'), ('movie', 'Фильм')], max_length=10, verbose_name='Тип произведения')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0, verbose_name='Число просмотров')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_quotes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_quotes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
